### ISSUE TITLE
Unable to pull ttrss-docker image

### ISSUE THREAD

**Issue by ALERTua** [sashkab/ttrss-docker#27]
`
docker-compose up --build --no-start
Pulling phpfpm (docker.pkg.github.com/sashkab/ttrss-docker/ttrss-docker:latest)...
ERROR: Get https://docker.pkg.github.com/v2/sashkab/ttrss-docker/ttrss-docker/manifests/latest: no basic auth credentials
`
How do I get the credentials for pulling the image?

**Comment by ALERTua** [comment]
workaround:
`docker login docker.pkg.github.com`
and then `docker-compose up --build`

**Comment by sashkab** [comment]
You don't need to use `--build` for `docker-compose`. These images are prebuilt already.

**Comment by ALERTua** [comment]
thanks. I'm new to Docker :)
