### ISSUE TITLE
Deploying rss/Dockerfile

### ISSUE THREAD

**Issue by ALERTua** [sashkab/ttrss-docker#28]
The cluster doesn't seem to deploy rss/Dockerfile. I deleted it and nothing changed.
And there is no ttrss git build pulling happens.
Even after I pulled the latest ttrss git to /app, it didn't work due to, I guess, the absence of /etc/php7/php-fpm.conf

**Comment by sashkab** [comment]
Umm... ttrss git pull happening when I build image, so don't really understand what you're saying. I'm currently use this and everything works for me. Perhaps show error logs, what you did and what happened.

**Comment by ALERTua** [comment]
sorry, I shouldn't have built the image.
